#!/usr/bin/env bash
set -o errexit -o nounset

[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly series="$2"
readonly cname="neo4j-$(uuidgen)"

docker_run "$image" "$cname" "NEO4J_1a=1 NEO4J_AUTH=none"
readonly ip="$(docker_ip "${cname}")"
neo4j_wait "${ip}"

stderr="$((docker logs "${cname}" 1>/dev/null) 2>&1)"

if [[ "${series}" == "2.3" ]]; then
  expected_err=""
else
  expected_err="WARNING: 1a not written to conf file because settings that start with a number are not permitted"
fi

if [[ "${stderr}" != "${expected_err}" ]]; then
    echo "Unexpected output from container:"
    echo "${stderr}"
    exit 1
fi
