#!/usr/bin/env bash
set -o errexit -o nounset
[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly cname="neo4j-$(uuidgen)"

docker_run "$image" "$cname" "NEO4J_AUTH=neo4j/foo"
neo4j_wait "$(docker_ip "${cname}")" "neo4j:foo"
neo4j_createnode "$(docker_ip "${cname}")" "neo4j:foo"

# Should start again when restarted
docker_restart "${cname}"
neo4j_wait "$(docker_ip "${cname}")" "neo4j:foo"
neo4j_createnode "$(docker_ip "${cname}")" "neo4j:foo"
