#!/usr/bin/env bash
set -o errexit -o nounset

[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly cname="neo4j-$(uuidgen)"

docker_run "$image" "$cname" "NEO4J_AUTH=none"
readonly ip="$(docker_ip "${cname}")"
neo4j_wait "${ip}"

# check no errors were printed to stderr
check_stderr_is_empty "${cname}"