#!/usr/bin/env bash
set -o errexit -o nounset

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly series="$2"
readonly edition="$3"

if ! [[ "${edition}" == "enterprise" ]]; then
  echo "Skipping: High-Availability only available in enterprise"
  exit 0
fi

if ! which docker-compose >/dev/null; then
  echo "Skipping: no docker-compose in path"
  exit 0
fi

# Make a temp copy of compose file
readonly compose_file=$(mktemp /tmp/XXXXXXXX.yml)
cp "$(dirname "$0")/ha-cluster-compose.yml" "${compose_file}"

readonly cname="core-$(uuidgen)"
readonly rname="slave-$(uuidgen)"

docker_compose_up "${image}" "${compose_file}" "${cname}" "${rname}"
readonly core_ip="$(docker_compose_ip "${cname}")"
readonly slave_ip="$(docker_compose_ip "${rname}")"
# Make sure core and read replica are up
neo4j_wait "${core_ip}" "" "120"
neo4j_wait "${slave_ip}" "" "120"

# create node on master
neo4j_createnode "${core_ip}" "neo4j:neo"
# read back on slave
neo4j_readnode "${slave_ip}" "neo4j:neo" "30"
