#!/usr/bin/env bash
set -o errexit -o nounset
[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly series="$2"
readonly cname="neo4j-$(uuidgen)"

docker_run_with_args "$image" "$cname" "--env=NEO4J_AUTH=neo4j/foo"
neo4j_wait "$(docker_ip "${cname}")" "neo4j:foo"
neo4j_createnode_pre_40 "$(docker_ip "${cname}")" "neo4j:foo"

# Should start again when restarted
docker_restart "${cname}"
neo4j_wait "$(docker_ip "${cname}")" "neo4j:foo"

if [[ "${series}" != "4.0" ]]; then
  neo4j_createnode_pre_40 "$(docker_ip "${cname}")" "neo4j:foo"
else
  neo4j_createnode "$(docker_ip "${cname}")" "neo4j:foo"
fi

# check no errors were printed to stderr
if [[ "${series}" == "2.3" ]] || [[ "${series}" == "3.0" ]]  || [[ "${series}" == "3.1" ]] || [[ "${series}" == "3.2" ]]; then
  echo "Skipping test for error message on change password"
  exit 0
fi

check_stderr_is_empty "${cname}"
