#!/usr/bin/env bash
set -o errexit -o nounset
[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly series="$2"
readonly cname="neo4j-$(uuidgen)"

if [[ "${series}" == "4.0" ]]; then
    echo "Skipping this test for now on 4.0"
    exit 0;
fi

docker_run_with_args "$image" "$cname" "--env=NEO4J_AUTH=neo4j/foo"
neo4j_wait "$(docker_ip "${cname}")" "neo4j:foo"
neo4j_createnode_pre_40 "$(docker_ip "${cname}")" "neo4j:foo"

# Should start again when restarted
docker_restart "${cname}"
neo4j_wait "$(docker_ip "${cname}")" "neo4j:foo"

if [[ "${series}" != "4.0" ]]; then
  neo4j_createnode_pre_40 "$(docker_ip "${cname}")" "neo4j:foo"
else
  neo4j_createnode "$(docker_ip "${cname}")" "neo4j:foo"
fi

# check no errors were printed to stderr
if [[ "${series}" == "2.3" ]] || [[ "${series}" == "3.0" ]]  || [[ "${series}" == "3.1" ]] || [[ "${series}" == "3.2" ]]; then
  echo "Skipping test for error message on change password"
  exit 0
fi

if [[ "${series}" == "4.0" ]]; then
    expected_40_err=`echo -e "WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by org.eclipse.collections.impl.utility.ArrayListIterate (file:/var/lib/neo4j/lib/eclipse-collections-9.2.0.jar) to field java.util.ArrayList.elementData\nWARNING: Please consider reporting this to the maintainers of org.eclipse.collections.impl.utility.ArrayListIterate\nWARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations\nWARNING: All illegal access operations will be denied in a future release"`
    check_stderr_matches "${cname}" "${expected_40_err}"
else
    check_stderr_is_empty "${cname}"
fi
