#!/usr/bin/env bash
set -o errexit -o nounset
[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly series="$2"
readonly cname="neo4j-$(uuidgen)"

if [[ "${series}" == "4.0" ]]; then
    echo "Skipping this test for now on 4.0"
    exit 0;
fi

docker_run "$image" "$cname" "NEO4J_AUTH=neo4j/foo"
neo4j_wait "$(docker_ip "${cname}")" "neo4j:foo"
#neo4j_createnode "$(docker_ip "${cname}")" "neo4j:foo"
neo4j_createnode_pre_40 "$(docker_ip "${cname}")" "neo4j:foo"

# Should start again when restarted
docker_restart "${cname}"
neo4j_wait "$(docker_ip "${cname}")" "neo4j:foo"
if [[ "${series}" != "4.0" ]]; then
  neo4j_createnode_pre_40 "$(docker_ip "${cname}")" "neo4j:foo"
else
  neo4j_createnode "$(docker_ip "${cname}")" "neo4j:foo"
fi
