#!/usr/bin/env bash
set -o errexit -o nounset

[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly cname="neo4j-$(uuidgen)"
readonly auth_password="N30-S3cr375!"
readonly credentials="neo4j/${auth_password}"

docker_run "$image" "$cname" "NEO4J_AUTH=${credentials}"
readonly ip="$(docker_ip "${cname}")"
neo4j_wait "${ip}" "neo4j:${auth_password}"

readonly result="$(neo4j_cypher "${cname}" "RETURN 123" "${credentials}")"
echo "RESULT: ${result}"
if ! echo "${result}" | grep -q "123"; then
  echo "Error running cypher"
  exit 1
else
  echo "cypher success"
fi

stderr="$((docker logs "${cname}" 1>/dev/null) 2>&1)"
if [[ "${stderr}" != "" ]]; then
    echo "Unexpected output from container:"
    echo "${stderr}"
    exit 1
fi
