#!/usr/bin/env bash
set -o errexit -o nounset

[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly cname="neo4j-$(uuidgen)"

docker_run "$image" "$cname" "NEO4J_AUTH=none"
readonly ip="$(docker_ip "${cname}")"
neo4j_wait "${ip}"

stderr="$((docker logs "${cname}" 1>/dev/null) 2>&1)"
if [[ "${stderr}" != "" ]]; then
    echo "Unexpected output from container:"
    echo "${stderr}"
    exit 1
fi
