#! /usr/bin/env python

import os
import sys

data = {
    '2.2.5': {
        'sha': '7fadc119f465a3d6adceb610401363fb158a5ed25081f9893d4f56ac4989a998',
    },
    'dev': {
        'version': os.environ['DEV_VERSION'],
        'sha': os.environ['DEV_SHA'],
        'root': 'file:///docker-test/',
        'inject': 'COPY ./neo4j-package.tar.gz /docker-test/$NEO4J_TARBALL',
    }
}

for version, details in data.iteritems():
    if not 'version' in details:
        details['version'] = version
    if not 'root' in details:
        details['root'] = 'http://dist.neo4j.org'
    if not 'inject' in details:
        details['inject'] = ''

print data[os.environ['VERSION']][sys.argv[1]]
