#!/usr/bin/env bash
set -o nounset

[[ -n "${TRACE:-}" ]] && set -o xtrace

. "$(dirname "$0")/helpers.sh"

readonly image="$1"
readonly series="$2"
readonly edition="$3"
readonly cname="neo4j-$(uuidgen)"

if [[ "${series}" == "2.3" ]] ||
    [[ "${series}" == "3.0" ]] ||
    [[ "${series}" == "3.1" ]] ||
    [[ "${series}" == "3.2" ]]; then
  echo "Skipping: License agreement acceptance not required pre-3.3"
  exit 0
fi

if ! [[ "${edition}" == "enterprise" ]]; then
  echo "Skipping: License agreement acceptance only required in enterprise"
  exit 0
fi

cid="$(docker run --detach --name="${cname}" "${image}")"
trap "docker rm --force ${cid} > /dev/null 2>&1" EXIT

# Wait until container exits before we check the logs
while docker top "${cid}" &>/dev/null
do
  sleep 1
done

log="$(docker logs "${cid}" 2>&1)"

if echo "${log}" | grep --quiet "must accept the license"; then
  echo "License agreement not accepted."
  exit 0
else
  echo >&2 "Not accepting the license agreement should have failed."
  cat >&2 "${log}"
  exit 1
fi
