#!/bin/bash -eu

CONFIG_FILE_PATH="${NEO4J_HOME}"/conf/neo4j.conf
LISTEN_ADDRESS_SETTING_NAME="server.http.listen_address"
LISTEN_ADDRESS_SETTING_NAME_PRE_5="dbms.connector.http.listen_address"

while [ ! -e $CONFIG_FILE_PATH ]
do
  sleep 1
done

if [ $(grep -P "^(?!#)"$LISTEN_ADDRESS_SETTING_NAME $CONFIG_FILE_PATH) ]
then
  LISTEN_ADDRESS_SETTING_STRING=$(grep -P "^(?!#)"$LISTEN_ADDRESS_SETTING_NAME $CONFIG_FILE_PATH)
  LISTEN_ADDRESS_SETTING_VALUE=${LISTEN_ADDRESS_SETTING_STRING#*=}
elif [ $(grep -P "^(?!#)"$LISTEN_ADDRESS_SETTING_NAME_PRE_5 $CONFIG_FILE_PATH) ]
then
  LISTEN_ADDRESS_SETTING_STRING=$(grep -P "^(?!#)"$LISTEN_ADDRESS_SETTING_NAME_PRE_5 $CONFIG_FILE_PATH)
    LISTEN_ADDRESS_SETTING_VALUE=${LISTEN_ADDRESS_SETTING_STRING#*=}
else
  LISTEN_ADDRESS_SETTING_VALUE=""
fi

if [ -z "${LISTEN_ADDRESS_SETTING_VALUE}" ]
then
  LISTEN_ADDRESS="http://localhost:7474/"
elif [[ ${LISTEN_ADDRESS_SETTING_VALUE} =~ (.){1,}:(\d){0,5} ]]
then
  LISTEN_ADDRESS=${LISTEN_ADDRESS_SETTING_VALUE}
elif [[ ${LISTEN_ADDRESS_SETTING_VALUE} =~ :(\d){0,5} ]]
then
  LISTEN_ADDRESS="http://localhost""${LISTEN_ADDRESS_SETTING_VALUE}""/"
else
  LISTEN_ADDRESS="${LISTEN_ADDRESS_SETTING_VALUE}"":7474/"
fi

if wget --accept=application/json ${LISTEN_ADDRESS} --output-document=tempfile
then
  exit 0
else
  exit 1
fi