name: Spotless

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Spotless check
        run: mvn spotless:check || echo >&2 "enable pre-commit checks by running \"pre-commit install\""
